# -*- coding: utf-8 -*-
"""tokenizers.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zw7UbXr_T56yIBsiVNUqoIjFe-DrbwUU
"""

def tokens(x):

    """  Function takes strings and tokenises using comma.    """   
  
    return x.split(',')